// All copy lives here, in both languages. Facts come from public/assets/Curriculo.pdf
// and the previous version of the site — nothing here is invented.

export const LINKS = {
  email: 'vargasvargasjoa@gmail.com',
  github: 'https://github.com/vargxrz',
  linkedin: 'https://linkedin.com/in/vargxrz',
  instagram: 'https://instagram.com/vargxrz',
  cv: '/assets/Curriculo.pdf',
};

const projects = {
  pt: [
    {
      name: 'Finassa',
      kind: 'Full stack',
      desc: 'Gestão de finanças pessoais: gastos, orçamentos e metas financeiras numa interface limpa.',
      tech: ['TypeScript', 'Next.js', 'Docker'],
      href: 'https://github.com/vargxrz/finassa',
    },
    {
      name: 'Movies Library',
      kind: 'Front-end',
      desc: 'Descoberta de filmes com React Router: busca e navegação responsivas.',
      tech: ['React', 'JavaScript', 'Vite'],
      href: 'https://github.com/vargxrz/movies-lib-react',
    },
    {
      name: 'Restaurant Menu',
      kind: 'Front-end',
      desc: 'Cardápio virtual responsivo para restaurantes, com animações suaves.',
      tech: ['HTML', 'CSS', 'JavaScript'],
      href: 'https://github.com/vargxrz/restaurant-menu',
    },
    {
      name: 'Push Notification',
      kind: 'Back-end',
      desc: 'POC em Java integrada ao Firebase Cloud Messaging para enviar push a apps mobile.',
      tech: ['Java', 'Firebase', 'FCM'],
      href: 'https://github.com/vargxrz/push-notification',
    },
  ],
  en: [
    {
      name: 'Finassa',
      kind: 'Full stack',
      desc: 'Personal finance management: spending, budgets and financial goals in a clean interface.',
      tech: ['TypeScript', 'Next.js', 'Docker'],
      href: 'https://github.com/vargxrz/finassa',
    },
    {
      name: 'Movies Library',
      kind: 'Frontend',
      desc: 'Movie discovery app with React Router: responsive search and browsing.',
      tech: ['React', 'JavaScript', 'Vite'],
      href: 'https://github.com/vargxrz/movies-lib-react',
    },
    {
      name: 'Restaurant Menu',
      kind: 'Frontend',
      desc: 'Responsive virtual menu for restaurants, with smooth animations.',
      tech: ['HTML', 'CSS', 'JavaScript'],
      href: 'https://github.com/vargxrz/restaurant-menu',
    },
    {
      name: 'Push Notification',
      kind: 'Backend',
      desc: 'Java POC integrated with Firebase Cloud Messaging to send push notifications to mobile apps.',
      tech: ['Java', 'Firebase', 'FCM'],
      href: 'https://github.com/vargxrz/push-notification',
    },
  ],
};

const stackGroups = {
  pt: [
    { name: 'Back-end', items: ['Java', 'Spring Boot', 'Spring Security', 'JWT', 'JPA', 'Hibernate', 'APIs REST'] },
    { name: 'Front-end & Mobile', items: ['React.js', 'JavaScript', 'HTML', 'CSS', 'Flutter Web', 'Flutter Mobile (Dart)'] },
    { name: 'Testes', items: ['TDD', 'JUnit', 'Mockito', 'MockMvc', 'Jest', 'Playwright'] },
    { name: 'Dados', items: ['PostgreSQL', 'MySQL'] },
    { name: 'Cloud & Infra', items: ['Amazon S3', 'AWS Bedrock', 'Docker', 'Terraform'] },
    { name: 'Ferramentas', items: ['Git', 'GitHub', 'Figma', 'Xcode', 'Twilio', 'Claude Code', 'GitHub Copilot', 'Opencode'] },
  ],
  en: [
    { name: 'Backend', items: ['Java', 'Spring Boot', 'Spring Security', 'JWT', 'JPA', 'Hibernate', 'REST APIs'] },
    { name: 'Frontend & Mobile', items: ['React.js', 'JavaScript', 'HTML', 'CSS', 'Flutter Web', 'Flutter Mobile (Dart)'] },
    { name: 'Testing', items: ['TDD', 'JUnit', 'Mockito', 'MockMvc', 'Jest', 'Playwright'] },
    { name: 'Data', items: ['PostgreSQL', 'MySQL'] },
    { name: 'Cloud & Infra', items: ['Amazon S3', 'AWS Bedrock', 'Docker', 'Terraform'] },
    { name: 'Tools', items: ['Git', 'GitHub', 'Figma', 'Xcode', 'Twilio', 'Claude Code', 'GitHub Copilot', 'Opencode'] },
  ],
};

const certifications = [
  'Spring Boot Expert — JPA, RESTful, Spring Security, JWT',
  'Fundamentos Java — OO, Programação Funcional, JavaFX, Hibernate',
  'Docker Completo — Do Zero ao Avançado',
  'Banco de Dados e Linguagem SQL com PostgreSQL',
  'Spring Boot Unit Testing with JUnit, Mockito and MockMvc',
  'UX Writing: Reescrevendo a Experiência do Usuário — FIAP',
];

export const CONTENT = {
  pt: {
    htmlLang: 'pt-BR',
    title: 'João Vargas — Desenvolvedor Full-stack',
    description: 'Desenvolvedor full-stack em Gaspar, SC. Java/Spring Boot, React e Flutter em produção, com testes automatizados.',
    skip: 'Pular para o conteúdo',
    nav: [
      { id: 'trabalho', label: 'Trabalho', key: '1' },
      { id: 'trajetoria', label: 'Trajetória', key: '2' },
      { id: 'stack', label: 'Stack', key: '3' },
      { id: 'contato', label: 'Contato', key: '4' },
    ],
    navShortcutsHint: 'Atalhos: teclas 1 a 4',
    commands: {
      open: 'Comandos secretos',
      title: 'Caderninho de comandos',
      hint: 'Digite na home ou clique pra rodar.',
      found: 'descobertos',
      list: [
        { word: 'vargas', desc: 'Meu nome: as teclas fazem a onda.' },
        { word: 'segredo', desc: 'Vista explodida das teclas + uma dica.' },
        { word: 'teste', desc: 'Roda um JUnit em cada tecla.' },
        { word: 'deploy', desc: 'Pipeline verde e as teclas decolam.' },
        { word: 'rgb', desc: 'Modo gamer: o laranja vira arco-íris.' },
        { word: 'gravidade', desc: 'Tudo cai. Toque na tela ou Esc arruma.' },
        { word: 'sagrav', desc: 'Site de cabeça pra baixo.' },
        { word: 'joao', desc: 'Chuva da minha stack.' },
        { word: 'ana', desc: '♥' },
        { word: 'poker', desc: 'As teclas viram um royal flush de paus.' },
        { word: 'renan', desc: 'Do Minecraft em 2018 ao Rio em 2026.' },
        { word: 'curbas', desc: 'Pro meu amigão.' },
      ],
    },
    themeToLight: 'Mudar para tema claro',
    themeToDark: 'Mudar para tema escuro',
    langSwitch: 'Read in English',
    langShort: 'EN',
    menu: 'Menu',
    close: 'Fechar',
    hero: {
      status: 'Disponível para oportunidades',
      location: 'Gaspar, SC — Brasil',
      role: 'Desenvolvedor Full-stack',
      titleA: 'Do Figma',
      titleB: 'ao deploy.',
      lede: 'Sou o João Vargas. Construo aplicações web e mobile de ponta a ponta — da modelagem no Figma e da arquitetura à implementação, aos testes automatizados e ao code review. Hoje, em produção na Segala’s Alimentos.',
      stack: ['Java · Spring Boot', 'React', 'Flutter'],
      ctaWork: 'Ver trabalho',
      ctaCv: 'Baixar currículo',
      ctaCvMeta: 'PDF',
      typeHint: 'Digite no seu teclado — as teclas respondem. Algumas palavras escondem surpresas.',
      touchHint: 'Toque nas teclas ou em Digitar. Algumas palavras escondem surpresas.',
      typeOpen: 'Digitar',
      typeClose: 'Fechar teclado',
      typeLabel: 'Digite um comando',
      bufferLabel: 'Você digitou',
      eggs: {
        vargas: 'Você digitou meu nome. Agora é só me chamar →',
        segredo: 'Psiu — o segredo é escrever o teste antes. Digite teste.',
        testeRunning: 'Rodando os testes do teclado…',
        teste: 'Bom garoto! Isso é TDD.',
        curbas: 'Salve, Curbas.',
        poker: 'Royal flush de paus. Digite poker de novo (ou Esc) pra recolher as cartas.',
        pokerOff: 'Cartas na mesa. De volta ao V A R G A S.',
        pokerCaption: 'Champion Start Free!',
        pokerAlt: 'Foto do João Vargas campeão num torneio de poker, segurando as cartas, com fichas e troféu na mesa',
        renan: 'Renan: amigo desde o Minecraft, em 2018. Em 2026, bloco por bloco, fomos parar no Rio.',
        renanOff: 'Blocos quebrados. De volta ao V A R G A S.',
        renanCaptions: ['RJ 2026', 'RJ 2026'],
        renanAlts: ['Selfie do João Vargas com o amigo Renan em frente ao Cristo Redentor, no Rio de Janeiro', 'Pôr do sol na pedra do Arpoador, com o mar de Ipanema e o morro Dois Irmãos ao fundo'],
        ana: 'Pra Ana. ♥',
        sagravOn: 'sagraV oãoJ. Digite sagrav de novo (ou Esc) pra desvirar.',
        sagravOff: 'Tudo no lugar de novo.',
        joao: 'Chuva de stack: tudo o que eu uso do Figma ao deploy.',
        rgbOn: 'Modo gamer ligado. Digite rgb de novo pra desligar.',
        rgbOff: 'RGB desligado. De volta ao profissional.',
        gravityOn: 'Opa. Digite gravidade de novo, aperte Esc ou toque na tela pra arrumar a bagunça.',
        gravityOff: 'Tudo no lugar. Ninguém viu nada.',
        deploy: 'Build ok, testes ok — deploy em produção. 🚀',
      },
      pipeline: ['build', 'testes', 'deploy'],
    },
    work: {
      index: '01',
      label: 'Trabalho',
      caseLabel: 'Caso em produção',
      caseMeta: 'Segala’s Alimentos · Flutter Web · Front-end completo',
      caseTitle: 'Auto cadastro de clientes',
      metricFrom: 'horas',
      metricTo: '2–3 min',
      metricCaption: 'para cadastrar um novo cliente',
      caseBody: 'Fui responsável por todo o front-end. O cliente informa o CNPJ e a interface se preenche sozinha com os dados que o back-end busca nas APIs da ReceitaWS e do CNPJ.já — o preenchimento manual caiu para poucos campos.',
      flowLabel: 'Fluxo do cadastro',
      steps: [
        { title: 'CNPJ', body: 'Dados da empresa retornados pelo back-end a partir da ReceitaWS e do CNPJ.já.', tag: 'APIs externas' },
        { title: 'Preenchimento automático', body: 'Informações do cliente mapeadas automaticamente na interface.', tag: 'Flutter Web' },
        { title: 'Documentos', body: 'Upload de documentos direto para o Amazon S3.', tag: 'Amazon S3' },
        { title: 'Validação com IA', body: 'Imagens enviadas validadas com AWS Bedrock.', tag: 'AWS Bedrock' },
        { title: 'Localização', body: 'Mapa interativo com coordenadas geográficas.', tag: 'Mapa' },
        { title: 'WhatsApp', body: 'Número confirmado por código enviado via Twilio.', tag: 'Twilio' },
      ],
      shippedTitle: 'Mais em produção',
      shipped: [
        {
          title: 'Autorização de preço e backoffice',
          stack: 'Flutter Web + Spring Boot',
          body: 'Refatorei o front-end inteiro aplicando padrões de design e criei o dashboard de gestão do auto cadastro, com controle de roles e permissões. No back-end, SQL no dia a dia para dar suporte operacional aos usuários.',
        },
        {
          title: 'E-commerce',
          stack: 'React.js + Spring Boot',
          body: 'Full-stack, das telas no Figma com auto layout até a revisão das funcionalidades na prática, com cenários de teste e code review. Destaque para as push notifications.',
        },
        {
          title: 'Força de vendas mobile',
          stack: 'Flutter Mobile + Spring Boot',
          body: 'Participei do desenvolvimento do aplicativo, com Xcode, simuladores iOS e fluxo de testes em dispositivo.',
        },
      ],
      testing: 'Testes com TDD: JUnit, Mockito e MockMvc no back-end; Jest e Playwright no front-end.',
      projectsTitle: 'Projetos pessoais',
      projectsNote: 'Código aberto no GitHub',
      projects: projects.pt,
      viewCode: 'Ver código',
    },
    journey: {
      index: '02',
      label: 'Trajetória',
      title: 'Do administrativo ao código.',
      lede: 'Aprendi Java, Spring Boot, bancos de dados, testes automatizados e desenvolvimento web de forma autodidata — e coloquei cada tecnologia em prática no produto real desde o primeiro dia.',
      items: [
        { when: 'jan 2021 — ago 2022', role: 'Auxiliar Administrativo', org: 'Acil Têxtil · Randa Mundu Confecções', body: 'Primeiros empregos, em Gaspar.' },
        { when: 'ago 2022 — out 2023', role: 'Estagiário', org: 'PepsiCo', body: 'Relatórios, cadastro de produtos e suporte a rotinas administrativas e logísticas em ambiente multinacional.' },
        { when: 'out 2023 — fev 2025', role: 'Desenvolvedor de Software Trainee', org: 'Segala’s Alimentos', body: 'POCs e pesquisa de soluções técnicas junto ao time, contribuindo para decisões de arquitetura.' },
        { when: 'fev 2025 — hoje', role: 'Desenvolvedor de Software Júnior', org: 'Segala’s Alimentos', body: 'Auto cadastro de clientes, backoffice, e-commerce e força de vendas em produção.', current: true },
      ],
      educationLabel: 'Formação',
      education: 'Bacharelado em Engenharia de Software — Anhanguera',
      educationWhen: 'ago 2026 — ago 2030 · em andamento',
      now: 'agora',
    },
    stack: {
      index: '03',
      label: 'Stack',
      title: 'Ferramentas do ofício.',
      lede: 'O que uso para levar uma ideia do Figma ao deploy — com testes no caminho.',
      groups: stackGroups.pt,
      certsTitle: 'Certificações',
      certs: certifications,
      languagesTitle: 'Idiomas',
      languages: ['Português — nativo', 'Inglês — intermediário', 'Espanhol — básico'],
    },
    contact: {
      index: '04',
      label: 'Contato',
      title: 'Vamos construir algo?',
      lede: 'Aberto a oportunidades e colaborações. Me chama por e-mail ou LinkedIn.',
      enterHint: 'Pressione Enter para copiar meu e-mail',
      touchHint: 'Toque na tecla para copiar meu e-mail',
      copied: 'E-mail copiado',
      copyFailed: 'Não deu para copiar — o e-mail está logo abaixo',
      emailLabel: 'E-mail',
      elsewhere: 'Em outros lugares',
    },
    footer: {
      top: 'Voltar ao topo',
    },
  },
  en: {
    htmlLang: 'en',
    title: 'João Vargas — Full-stack Developer',
    description: 'Full-stack developer from Gaspar, Brazil. Java/Spring Boot, React and Flutter in production, with automated tests.',
    skip: 'Skip to content',
    nav: [
      { id: 'trabalho', label: 'Work', key: '1' },
      { id: 'trajetoria', label: 'Journey', key: '2' },
      { id: 'stack', label: 'Stack', key: '3' },
      { id: 'contato', label: 'Contact', key: '4' },
    ],
    navShortcutsHint: 'Shortcuts: keys 1 to 4',
    commands: {
      open: 'Secret commands',
      title: 'Command notebook',
      hint: 'Type them on the home screen, or click to run.',
      found: 'found',
      list: [
        { word: 'vargas', desc: 'My name: the keys do the wave.' },
        { word: 'segredo', desc: 'Exploded view of the keys + a hint.' },
        { word: 'teste', desc: 'Runs a JUnit test on every key.' },
        { word: 'deploy', desc: 'Green pipeline, then the keys lift off.' },
        { word: 'rgb', desc: 'Gamer mode: the orange goes rainbow.' },
        { word: 'gravity', desc: 'Everything falls. Tap or Esc tidies up.' },
        { word: 'sagrav', desc: 'The site, upside down.' },
        { word: 'joao', desc: 'A shower of my stack.' },
        { word: 'ana', desc: '♥' },
        { word: 'poker', desc: 'The keys turn into a royal flush in clubs.' },
        { word: 'renan', desc: 'From Minecraft in 2018 to Rio in 2026.' },
        { word: 'curbas', desc: 'For my buddy.' },
      ],
    },
    themeToLight: 'Switch to light theme',
    themeToDark: 'Switch to dark theme',
    langSwitch: 'Ler em português',
    langShort: 'PT',
    menu: 'Menu',
    close: 'Close',
    hero: {
      status: 'Available for opportunities',
      location: 'Gaspar, SC — Brazil',
      role: 'Full-stack Developer',
      titleA: 'From Figma',
      titleB: 'to deploy.',
      lede: 'I’m João Vargas. I build web and mobile apps end to end — from Figma models and architecture to implementation, automated tests and code review. Currently shipping to production at Segala’s Alimentos.',
      stack: ['Java · Spring Boot', 'React', 'Flutter'],
      ctaWork: 'See the work',
      ctaCv: 'Download résumé',
      ctaCvMeta: 'PDF · PT',
      typeHint: 'Type on your keyboard — the keys respond. Some words hide surprises.',
      touchHint: 'Tap the keys or Type. Some words hide surprises.',
      typeOpen: 'Type',
      typeClose: 'Close keyboard',
      typeLabel: 'Type a command',
      bufferLabel: 'You typed',
      eggs: {
        vargas: 'You typed my name. Now just reach out →',
        segredo: 'Psst — the secret is writing the test first. Type teste.',
        testeRunning: 'Running the keyboard tests…',
        teste: 'Good boy! That’s TDD.',
        curbas: 'Salve, Curbas.',
        poker: 'Royal flush in clubs. Type poker again (or Esc) to fold.',
        pokerOff: 'Cards down. Back to V A R G A S.',
        pokerCaption: 'Champion Start Free!',
        pokerAlt: 'Photo of João Vargas winning a poker tournament, holding his cards, with chips and a trophy on the table',
        renan: 'Renan: friends since Minecraft, back in 2018. In 2026, block by block, we made it to Rio.',
        renanOff: 'Blocks mined. Back to V A R G A S.',
        renanCaptions: ['RJ 2026', 'RJ 2026'],
        renanAlts: ['Selfie of João Vargas and his friend Renan in front of Christ the Redeemer, Rio de Janeiro', 'Sunset from the Arpoador rock, with Ipanema beach and the Dois Irmãos hill behind'],
        ana: 'For Ana. ♥',
        sagravOn: 'sagraV oãoJ. Type sagrav again (or Esc) to flip back.',
        sagravOff: 'Everything back in place.',
        joao: 'Stack shower: everything I use from Figma to deploy.',
        rgbOn: 'Gamer mode on. Type rgb again to turn it off.',
        rgbOff: 'RGB off. Back to business.',
        gravityOn: 'Oops. Type gravity again, press Esc or tap the screen to clean up.',
        gravityOff: 'All back in place. Nobody saw anything.',
        deploy: 'Build ok, tests ok — shipped to production. 🚀',
      },
      pipeline: ['build', 'tests', 'deploy'],
    },
    work: {
      index: '01',
      label: 'Work',
      caseLabel: 'Shipped case',
      caseMeta: 'Segala’s Alimentos · Flutter Web · Entire frontend',
      caseTitle: 'Customer self-registration',
      metricFrom: 'hours',
      metricTo: '2–3 min',
      metricCaption: 'to register a new customer',
      caseBody: 'I owned the whole frontend. The customer enters their CNPJ (company tax ID) and the interface fills itself in with the data the backend fetches from the ReceitaWS and CNPJ.já APIs — manual typing dropped to a handful of fields.',
      flowLabel: 'Registration flow',
      steps: [
        { title: 'CNPJ', body: 'Company data returned by the backend from ReceitaWS and CNPJ.já.', tag: 'External APIs' },
        { title: 'Auto-fill', body: 'Customer information mapped into the interface automatically.', tag: 'Flutter Web' },
        { title: 'Documents', body: 'Document upload straight to Amazon S3.', tag: 'Amazon S3' },
        { title: 'AI validation', body: 'Uploaded images validated with AWS Bedrock.', tag: 'AWS Bedrock' },
        { title: 'Location', body: 'Interactive map with geographic coordinates.', tag: 'Map' },
        { title: 'WhatsApp', body: 'Phone number confirmed with a code sent via Twilio.', tag: 'Twilio' },
      ],
      shippedTitle: 'Also in production',
      shipped: [
        {
          title: 'Price authorization & backoffice',
          stack: 'Flutter Web + Spring Boot',
          body: 'Rebuilt the entire frontend applying design patterns and built the dashboard that manages self-registration, with roles and permissions. On the backend, daily SQL work to support operations.',
        },
        {
          title: 'E-commerce',
          stack: 'React.js + Spring Boot',
          body: 'Full-stack, from Figma screens with auto layout to reviewing features in practice, with test scenarios and code review. Highlight: push notifications.',
        },
        {
          title: 'Mobile sales force app',
          stack: 'Flutter Mobile + Spring Boot',
          body: 'Worked on the app with Xcode, iOS simulators and an on-device testing flow.',
        },
      ],
      testing: 'Test-driven: JUnit, Mockito and MockMvc on the backend; Jest and Playwright on the frontend.',
      projectsTitle: 'Side projects',
      projectsNote: 'Open source on GitHub',
      projects: projects.en,
      viewCode: 'View code',
    },
    journey: {
      index: '02',
      label: 'Journey',
      title: 'From admin desk to code.',
      lede: 'I taught myself Java, Spring Boot, databases, automated testing and web development — and put each one to work in a real product from day one.',
      items: [
        { when: 'Jan 2021 — Aug 2022', role: 'Administrative Assistant', org: 'Acil Têxtil · Randa Mundu Confecções', body: 'First jobs, in Gaspar.' },
        { when: 'Aug 2022 — Oct 2023', role: 'Intern', org: 'PepsiCo', body: 'Reports, product registration and support for administrative and logistics routines in a multinational setting.' },
        { when: 'Oct 2023 — Feb 2025', role: 'Software Developer Trainee', org: 'Segala’s Alimentos', body: 'POCs and technical research alongside the team, contributing to architecture decisions.' },
        { when: 'Feb 2025 — now', role: 'Junior Software Developer', org: 'Segala’s Alimentos', body: 'Customer self-registration, backoffice, e-commerce and sales force apps in production.', current: true },
      ],
      educationLabel: 'Education',
      education: 'B.Sc. in Software Engineering — Anhanguera',
      educationWhen: 'Aug 2026 — Aug 2030 · in progress',
      now: 'now',
    },
    stack: {
      index: '03',
      label: 'Stack',
      title: 'Tools of the trade.',
      lede: 'What I use to take an idea from Figma to deploy — with tests along the way.',
      groups: stackGroups.en,
      certsTitle: 'Certifications',
      certs: certifications,
      languagesTitle: 'Languages',
      languages: ['Portuguese — native', 'English — intermediate', 'Spanish — basic'],
    },
    contact: {
      index: '04',
      label: 'Contact',
      title: 'Let’s build something?',
      lede: 'Open to opportunities and collaborations. Reach me by email or LinkedIn.',
      enterHint: 'Press Enter to copy my email',
      touchHint: 'Tap the key to copy my email',
      copied: 'Email copied',
      copyFailed: 'Couldn’t copy — the address is right below',
      emailLabel: 'Email',
      elsewhere: 'Elsewhere',
    },
    footer: {
      top: 'Back to top',
    },
  },
};
